# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(621, 446)
        self.buttonBox_final = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox_final.setGeometry(QtCore.QRect(190, 370, 341, 32))
        self.buttonBox_final.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_final.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_final.setCenterButtons(False)
        self.buttonBox_final.setObjectName("buttonBox_final")
        self.comboBox_format = QtWidgets.QComboBox(Dialog)
        self.comboBox_format.setGeometry(QtCore.QRect(60, 90, 69, 22))
        self.comboBox_format.setObjectName("comboBox_format")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.label_format = QtWidgets.QLabel(Dialog)
        self.label_format.setGeometry(QtCore.QRect(60, 70, 47, 13))
        self.label_format.setObjectName("label_format")
        self.label_url = QtWidgets.QLabel(Dialog)
        self.label_url.setGeometry(QtCore.QRect(60, 140, 47, 13))
        self.label_url.setObjectName("label_url")
        self.lineEdit_url = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_url.setGeometry(QtCore.QRect(60, 160, 481, 20))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 230, 481, 131))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 210, 47, 13))
        self.label.setObjectName("label")
        self.label_path = QtWidgets.QLabel(Dialog)
        self.label_path.setGeometry(QtCore.QRect(160, 70, 47, 13))
        self.label_path.setObjectName("label_path")
        self.lineEdit_path = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_path.setGeometry(QtCore.QRect(160, 90, 371, 20))
        self.lineEdit_path.setObjectName("lineEdit_path")

        self.retranslateUi(Dialog)
        self.buttonBox_final.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox_final.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox_format.setItemText(0, _translate("Dialog", "MP4"))
        self.comboBox_format.setItemText(1, _translate("Dialog", "MP3"))
        self.label_format.setText(_translate("Dialog", "Format"))
        self.label_url.setText(_translate("Dialog", "URL"))
        self.label.setText(_translate("Dialog", "Output"))
        self.label_path.setText(_translate("Dialog", "Path"))
